/*
 * servo12c_params.c
 *
 *  Created on: Dec 1, 2013
 *      Author: acebulla
 *
 */

#include <drivers/drv_servo12c.h>

/* controller parameters */
PARAM_DEFINE_FLOAT(PAN_P1_ABS, 0.0f);
PARAM_DEFINE_FLOAT(PAN_P1_DEG, 0.0f);
PARAM_DEFINE_FLOAT(PAN_P1_RAD, 0.0f);

PARAM_DEFINE_FLOAT(PAN_P2_ABS, 255.0f);
PARAM_DEFINE_FLOAT(PAN_P2_DEG, 180.0f);
PARAM_DEFINE_FLOAT(PAN_P2_RAD, PI);

PARAM_DEFINE_FLOAT(TILT_P1_ABS, 0.0f);
PARAM_DEFINE_FLOAT(TILT_P1_DEG, 0.0f);
PARAM_DEFINE_FLOAT(TILT_P1_RAD, 0.0f);

PARAM_DEFINE_FLOAT(TILT_P2_ABS, 255.0f);
PARAM_DEFINE_FLOAT(TILT_P2_DEG, 180.0f);
PARAM_DEFINE_FLOAT(TILT_P2_RAD, PI);
